print('Please enter the following: \n')
adjetive = input('adjetive: ')
animal = input('animal: ')
verb = input('verb: ')
exclamation = input('exclamation: ')
verb_1 = input('verb: ')
verb_2 = input('verb: ')
family_member = input('family_member: ')
verb_3 = input('verb: ')
verb_4 = input('verb: ')
adjetive_1 = input('adjetive: ')
thing = input('thing: ')
thing_1 = input('thing: ')

print('\nYour history is:\n')
print(f'The other day, I was really in trouble. It all started when I saw a very\n{adjetive} {animal} {verb} down the hallway. "{exclamation.capitalize()}!" I yelled. But all\nI could think to do was to {verb_1} over and over. Miraculously, \nthat caused it to stop, but not before it tried to {verb_2} \nright in front of my family. Then, my {family_member} runs beside me and\nstarted to {verb_3} with energy, my whole family were watching us.\nAfter a couple of minutes I leave the house, It was time to {verb_4}! I was \nprepared, using my {adjetive_1} {thing} and one {thing_1},\nnothing could stop me.\n')
